Users can view their entries
Korneliu/code-journal pull request #6
Opened 2021-11-03 05:16 UTC by Korneliu

![code-journal-issue-2](https://user-images.githubusercontent.com/25681013/140012850-e8e68c7d-d10a-44ee-a3d3-1da30e8ce541.gif)

2021-11-03 18:08 UTC, codingcodymiller requested changes
Hey Max! Your entries view is still visible under your entry form in your gif. there should only ever be one view visible at any time, all other views should be hidden from the user entirely. Make sure to upload a new gif once you submit your revisions 🤓

2021-11-04 04:15 UTC, Korneliu commented
![code-journal-issue-2](https://user-images.githubusercontent.com/25681013/140257082-1496b869-24fc-481d-8117-f33d234572e1.gif)

2021-11-04 19:30 UTC, codingcodymiller requested changes

2021-11-04 19:30 UTC, codingcodymiller commented on js/main.js
> +    switchingViews(data.view);
You can do this above or below the loop, it doesn't need to be done on each iteration.

2021-11-04 19:38 UTC, codingcodymiller approved these changes

2021-11-04 19:39 UTC, merged